### ISSUE TITLE
Overwrite assumes '/bin/cp' is available

### ISSUE THREAD

**Issue by klauspost** [glycerine/bambam#14]
Here https://github.com/glycerine/bambam/blob/master/bam.go#L668  it is assumed that /bin/cp is available.

On Windows that is not the case, and I assume it is also a bit unsafe on other platforms.

Here is what seems like a good file copy function in golang: http://stackoverflow.com/a/21067803

**Comment by glycerine** [comment]
Hi @klauspost, thanks for your suggestion. Would you mind preparing a pull request for this?

**Comment by glycerine** [comment]
@klauspost Please test on windows and let me know if there are any remaining issues. Thanks!
