### ISSUE TITLE
Support for uint8, uint16, and uint32 fields in structs

### ISSUE THREAD

**Issue by dmccurley** [glycerine/bambam#15]
Hello, great project!  I've just started experimenting and have found that the uint types mentioned in the subject don't seem to be supported fully.  If I have a struct like so that I generate capnp from:

```go
type Envelope struct {
	Ver   uint8  `capid:"0"`
	SvcId string `capid:"1"`
}
```

then the test below fails on the last 2 "if" statements.  It appears as if the bytes are serializing / deserializing correctly but the "Ver" field is being set to its go default value rather than the value from the deserialized bytes:

```go
func TestSerializationBytes(t *testing.T) {
	source := Envelope{
		Ver:   1,
		SvcId: "Svc1",
	}

	var o bytes.Buffer
	source.Save(&o)
	oBytes := o.Bytes()

	sink := &Envelope{}
	sink.Load(bytes.NewReader(oBytes))

	var o2 bytes.Buffer
	sink.Save(&o2)
	o2Bytes := o2.Bytes()

	if bytes.Compare(oBytes, o2Bytes) != 0 {
		t.Errorf("Source and Sink Envelope bytes do not match: %v -- %v", source, sink)
	}

	if source.SvcId != sink.SvcId {
		t.Errorf("source.SvcId: %v != sink.SvcId", source.SvcId, sink.SvcId)
	}

	if source.Ver != sink.Ver {
		t.Errorf("source.Ver: %v != sink.Ver: %v", source.Ver, sink.Ver)
	}

	if !reflect.DeepEqual(&source, sink) {
		t.Errorf("Structures do not match: %+v vs %+v", source, sink)
	}
}
```

Do you plan to support these uint types?

**Comment by glycerine** [comment]
Hi @dmccurley, thanks for noting this. I can confirm it does seem to be a problem.

It would be lovely to support this, but I don't have time just now. I you would be so kind as to prepare a pull request with a fix, I would be happy to incorporate it.  Otherwise you may have to make due with signed ints.

Jason

**Comment by glycerine** [comment]
@dmccurley Please test it out and let me know how it works for you. Thanks! - Jason

**Comment by dmccurley** [comment]
Thanks!  I'll check it out.
