### ISSUE TITLE
bambam -OVERWRITE does not work

### ISSUE THREAD

**Issue by HyperDrummer** [glycerine/bambam#16]
Hi,
calling 

bambam -OVERWRITE file.go

does not work (anymore)

output ==>

panic: open /: is a directory

goroutine 1 [running]:
main.(*Extractor).CopySourceFilesAddCapidTag(0x208362000, 0x0, 0x0)
        /go/src/github.com/glycerine/bambam/bam.go:659 +0x7ef
main.MainArgs(0x208310000, 0x3, 0x3)
        /go/src/github.com/glycerine/bambam/main.go:156 +0x12e4
main.main()
        /go/src/github.com/glycerine/bambam/main.go:30 +0x42

I assume that this is related to this change here:
https://github.com/glycerine/bambam/commit/58f48a1b4f2530d40b967f0b4d8696a9635ed61f

Btw.: I'm working on a mac

**Comment by glycerine** [comment]
@HyperDrummer, thanks for the report, I'll take a look.
