### ISSUE TITLE
Save/Load methods are not returning error

### ISSUE THREAD

**Issue by husio** [glycerine/bambam#4]
`bambam` is generating two methods for structures - `Save(io.Writer)` and `Load(io.Reader)`. Code generated is hiding errors instead of returning them:

* `Save` is writing to buffer, but it ignores error returned by `Segment.WriteTo`
* `Load` is reading from reader, but istead of returning an error it's panicking.

My proposal is to change both methods to return error interface. 
I'm happy to implement the change and provide pull request, I just want to know if my suggestion is good.

Here's example generated code:

```go
func (s *Foo) Save(w io.Writer) {
  	seg := capn.NewBuffer(nil)
  	FooGoToCapn(seg, s)
  	seg.WriteTo(w)  
}
 
func (s *Foo) Load(r io.Reader) {
  	capMsg, err := capn.ReadFromStream(r, nil)
  	if err != nil {
  		panic(fmt.Errorf("capn.ReadFromStream error: %s", err))

  	}
  	z := ReadRootFooCapn(capMsg)
      FooCapnToGo(z, s)
}
```

**Comment by glycerine** [comment]
@husio, that is a good idea. I'm happy to review your pull request.

**Comment by husio** [comment]
I did not manage to make the tests work, which means I don't have anything worth sharing. I decided to use protobuf instead of working further on cpnproto integration, because it's more mature and seems to better fits my needs. This means I will not work on this issue anymore.
I think that the issue is still valid though.

**Comment by glycerine** [comment]
@husio Protobuf is a great way to go. If you don't need capnproto performance, gogoprotobuf has alot more features.
I just pushed changes that implement your suggestion.
