### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jgoodall** [glycerine/bambam#5]
Attempting to install on Mac 10.9.5, 
Installed pre-requisites:
```brew install capnp
go get github.com/glycerine/go-capnproto```

Tried to install `bambam`:
```
$ go version
go version go1.4.1 darwin/amd64
$ go get -t github.com/glycerine/bambam
# github.com/glycerine/bambam
../../../../github.com/glycerine/bambam/main.go:56: undefined: LASTGITCOMMITHASH```

**Comment by glycerine** [comment]
Please read the README again. It addresses exactly this question. In the "to install" section:

~~~
# ignore the initial compile error about 'undefined: LASTGITCOMMITHASH'. `make` will fix that.
$ cd $GOPATH/src/github.com/glycerine/bambam
$ make  # runs tests, build if all successful
$ go install
~~~

**Comment by jgoodall** [comment]
Thanks for the quick reply, should have been paying better attention to readme... By the way, dont need to do the `go install`, just:
```shell
go get -t github.com/glycerine/bambam
cd $GOPATH/src/github.com/glycerine/bambam && make
```
