### ISSUE TITLE
go generate question

### ISSUE THREAD

**Issue by jgoodall** [glycerine/bambam#6]
Would it be possible to add the ability to use go 1.4's new [generate](http://blog.golang.org/generate) tool:
`//go:generate bambam $GOFILE`

So that you can create files using `go generate`?

**Comment by glycerine** [comment]
I welcome pull requests. Give it a try and let me know if it works.

**Comment by glycerine** [comment]
Generally though, since certain parts of golang are better in the 1.2 and 1.3 series, (namely debugging info for gdb, and calls into C are faster) I wouldn't require the later, slower go1.4 at this point.
